name: React Firebase CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_test_deploy:
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.1

      - name: Install Dependencies
        run: |
          yarn install
        working-directory: app

      - name: Build
        run: |
          yarn build
        working-directory: app

      - name: Test
        run: |
          yarn test aqC
        working-directory: app

      - name: Install Firebase Tools
        run: |
          npm install -g firebase-tools
        working-directory: app

      - name: Deploy
        env:
          FIREBASE_TOKEN_PROD: ${{ secrets.FIREBASE_TOKEN_PROD }}
        run: |
          firebase deploy --project original-covid-app --token $FIREBASE_TOKEN_PROD
        working-directory: app